line-length = 79
target-version="py311"
src = ["src"]

include = ["src/**.py", "tests/**.py"]

lint.select = [
"ALL"
]
lint.ignore = [
   "ARG",
   "ANN",
   "D",
   "EM101",
   "EM102",
   "PT001",
   "PT023",
   "SIM108",
   "SIM114",
   "TRY003",
   "PLW2901",
   "RET505",
   "PLR0913",
   "RUF001",
]

[lint.per-file-ignores]
"tests/**" = ["TID252", "PLR2004", "S101"]

[lint.isort]
no-lines-before = ["local-folder"]

[lint.flake8-tidy-imports]
ban-relative-imports = "parents"

[lint.flake8-quotes]
docstring-quotes = "double"
inline-quotes = "single"
